language: node_js
node_js:
- node
- lts/dubnium
- lts/carbon
env:
  global:
    secure: OIN8IWAmpeo7Gp/MF0zizjhWYUag1tJek0yt8DGmq99nI1vIvy6pxj+uey4iSGLwulAE/p59OC9MNt0K+Er+R4Zkb3D7ACSYTQztltB2X7tYTvFptV4tbzQkiwgJIiBeCVD7vJoTDoFmJpkX4bv5qjquCwiDcVYoSiQEWZkP5kQ=
install: npm install
script:
- npm run lint
- npm test
after_success:
- npm install coveralls
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
jobs:
  include:
  - stage: npm release
    node_js: lts/dubnium
    install: npm install
    script: npm run build
    deploy:
      provider: npm
      skip_cleanup: true
      email: egy186@yahoo.co.jp
      api_key:
        secure: UWdDk1rdHkGUryAh1aCg13ZBemOoHnTECGoy3EeUVMefIRpHrT9XwTrFomf6+1ZiWyMS7RahqkawTScZKiLISOuYrVgQ0lAtYYE3tzo8zZ7HfzVqg6xR0tAHlfDNtIQiHnujBa9jNuy+3QnbqRSyIFObxoAgWndX1cot74V2dJA=
      on:
        all_branches: true
        repo: egy186/icojs
        tags: true
    after_success: true
